[project]
name = "gen-ai-local-recipes"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Paul R Saxman", email = "saxman@gmail.com" }
]
requires-python = ">=3.12"
dependencies = [
    "ipykernel",
    "ipywidgets",
    "torch",
    "torchvision",
    "transformers",
    "accelerate",
    "bitsandbytes",
]

[project.optional-dependencies]
diffusers = [
    "diffusers",
    "sentencepiece",
    "protobuf",
    "gguf",
]

[tool.uv.sources]
diffusers = { git = "https://github.com/huggingface/diffusers" }

[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[tool.setuptools.packages.find]
where = ["."]
include = ["src"]
